fix: fix option

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -39,11 +39,19 @@ runs:
     - run: |
         opts=""
         if [ "$IGNORE" = "true" ]; then
-          opts="--ignore-unknown-commit"
+          opts="--ignore-not-linked-commit"
         fi
-        if ! deny-self-approve $opts validate --dismiss; then
+        tempfile=$(mktemp)
+        if ! deny-self-approve $opts validate --dismiss 2> >(tee -a "$tempfile" >&2); then
+          if grep -q "commit isn't linked to GitHub Users" "$tempfile"; then
+            echo "::error:: Commits aren't linked to GitHub Users. Please fix git config. https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user" >&2
+            exit 1
+          fi
           echo "::error:: Approval is required from anyone who did not push commits to the pull request https://github.com/suzuki-shunsuke/deny-self-approve-action" >&2
           exit 1
+        fi
+        if grep -q "commit isn't linked to GitHub Users" "$tempfile"; then
+          echo "::warn:: Commits aren't linked to GitHub Users. Please fix git config. https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user" >&2
         fi
       shell: bash
       env:
