chore: update deny-self-approve to v0.2.4 (#15)
* chore: update deny-self-approve to v0.2.4

* fix: fix the error message

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -40,7 +40,7 @@ runs:
         echo "has_not_linked_commit=false" >> "$GITHUB_OUTPUT"
         if ! deny-self-approve validate --dismiss 2> >(tee -a "$tempfile" >&2); then
           if grep -q "commit isn't linked to a GitHub User" "$tempfile"; then
-            echo "::error:: Commit isn't linked to a GitHub User. Please fix git config. https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user" >&2
+            echo "::error:: Commit isn't linked to a GitHub User. https://github.com/suzuki-shunsuke/deny-self-approve/blob/main/docs/001.md" >&2
             echo "has_not_linked_commit=true" >> "$GITHUB_OUTPUT"
             exit 1
           fi
