fix: abandon comment

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -8,16 +8,12 @@ inputs:
   github_token:
     description: |
       GitHub Access Token
-      pull_requests:write - Dismiss approvals and post comments
+      pull_requests:write - Dismiss approvals
     required: false
-  comment:
-    description: Whether this action posts a comment
-    required: false
-    default: "false"
 runs:
   using: composite
   steps:
-    # Install deny-self-approve and github-comment by aqua
+    # Install deny-self-approve by aqua
     - run: echo "value=$GITHUB_ACTION_PATH/aqua/aqua.yaml" >> "$GITHUB_OUTPUT"
       id: aqua_config
       shell: bash
@@ -29,38 +25,17 @@ runs:
         AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
 
     - shell: bash
-      run: github-comment -v
-      if: inputs.comment == 'true'
-      env:
-        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
-        GITHUB_TOKEN: ${{ steps.token.outputs.token }}
-    - shell: bash
       run: deny-self-approve -v
       env:
         AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
         GITHUB_TOKEN: ${{ steps.token.outputs.token }}
 
     - run: |
-        if ! github-comment exec \
-          -k deny-self-approve \
-          --config "$GITHUB_ACTION_PATH/github-comment.yaml" \
-          -- deny-self-approve validate --dismiss; then
-          echo "::error:: Approval is required from anyone who did not push commits to the pull request" >&2
-          exit 1
-        fi
-      shell: bash
-      if: inputs.comment == 'true'
-      env:
-        AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
-        GITHUB_TOKEN: ${{github.token}}
-
-    - run: |
         if ! deny-self-approve validate --dismiss; then
-          echo "::error:: Approval is required from anyone who did not push commits to the pull request" >&2
+          echo "::error:: Approval is required from anyone who did not push commits to the pull request https://github.com/suzuki-shunsuke/deny-self-approve-action" >&2
           exit 1
         fi
       shell: bash
-      if: inputs.comment != 'true'
       env:
         AQUA_CONFIG: ${{ steps.aqua_config.outputs.value }}
         GITHUB_TOKEN: ${{github.token}}
